name: CI (macOS)

on:
  push:
    paths:
    - '.github/workflows/**'
    - '3rdparty/**'
    - 'scripts/**'
    - 'src/**'
    - 'COPYING'
    - 'makefile'
  pull_request:
    paths:
    - '.github/workflows/**'
    - '3rdparty/**'
    - 'scripts/**'
    - 'src/**'
    - 'COPYING'
    - 'makefile'

permissions:
  contents: read

jobs:
  build-macos:
    strategy:
      matrix:
        include:
          - compiler: clang-arm64
            os: macos-latest
            arch: arm64
            executable: mame
          - compiler: clang-x64
            os: macos-15-intel
            arch: x86_64
            executable: mame
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0

    - name: Clean Homebrew taps & install dependencies
      env:
        HOMEBREW_NO_AUTO_UPDATE: 1
      run: |
        brew untap aws/tap || true
        brew install python3 sdl3

    - name: Build
      env:
        OVERRIDE_CC: clang
        OVERRIDE_CXX: clang++
        USE_LIBSDL: 1
        TOOLS: 1
      run: |
        make -j$(sysctl -n hw.ncpu)

    - name: Validate
      run: ./${{ matrix.executable }} -validate

    - name: Package Binaries
      if: startsWith(github.ref, 'refs/tags/mame')
      run: |
        strip ${{ matrix.executable }} chdman unidasm
        zip -r ${{ github.ref_name }}_macos_${{ matrix.arch }}.zip ${{ matrix.executable }} chdman unidasm

    - uses: actions/upload-artifact@v4.4.3
      with:
        name: ${{ matrix.executable }}-macos-${{ matrix.arch }}-${{ matrix.compiler }}
        path: |
          *.zip
          ${{ matrix.executable }}
          chdman
          unidasm
        if-no-files-found: error

  release:
    needs: build-macos
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/mame')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          path: ./all_artifacts

      - name: Move files for release
        run: |
          mkdir ./out
          find ./all_artifacts -name "*.zip" -exec cp {} ./out/ \;

      - name: Create Release
        uses: softprops/action-gh-release@v2.1.0
        with:
          name: Release ${{ github.ref_name }}
          files: ./out/*.zip
          generate_release_notes: false
          append_body: true
          draft: false
          prerelease: false